### PR TITLE
bump libcal to 0.4.4.50, drop CTK 11 support

### PR DESCRIPTION
**Pull request by billysuh7**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

CTK 11 support is dropped because no future consumer(dependee) will need CTK 11 version. Also there is no source tarball for CTK 11. 

This PR is considered part of https://github.com/conda-forge/staged-recipes/issues/27809 because cuSolverMp will need this libcal version.

### CODE REVIEW

**Comment by billysuh7** [comment]
@conda-forge-admin, please restart ci

**Comment by billysuh7** [comment]
@conda-forge-admin, please restart ci

**Comment by adibbley** [comment]
Can we use https://github.com/conda-forge/libcal-feedstock/pull/4 since this was part of the cublasmp release?

**Comment by billysuh7** [comment]
Dupe of https://github.com/conda-forge/libcal-feedstock/pull/4

**Pull request closed without merging**
