### PR TITLE
Update for cuBLASMp 0.3.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cublasmp-feedstock/issues/3

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
NOTE: CUDA 11 is dropped upstream starting this release.

**Review by billysuh7 — APPROVED** [review]
LGTM!

**Comment by adibbley** [comment]
@mrogowski can you also confirm the added dependency is only for libcublasmp, and we can go ahead with libcal? ref https://github.com/conda-forge/cublasmp-feedstock/issues/3#issuecomment-2455362489

**Comment by almogsegal** [comment]
> @mrogowski can you also confirm the added dependency is only for libcublasmp, and we can go ahead with libcal? ref [conda-forge/cublasmp-feedstock#3 (comment)](https://github.com/conda-forge/cublasmp-feedstock/issues/3#issuecomment-2455362489)

Yes, nvshmem is a dependency of libcublasmp only.

**Review by mrogowski — APPROVED** [review]

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
